# Generated by Django 4.0.4 on 2022-05-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembros',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembros',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
