# Generated by Django 4.0.4 on 2022-05-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0003_miembros_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
