# Generated by Django 4.0.4 on 2022-05-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0004_alter_miembros_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
